### ISSUE TITLE
create keys with aws_kms

### ISSUE THREAD

**Issue by michaelmckirchner** [ansible/proposals#82]
# Proposal: create keys with aws_kms module

*Author*: Michael Kirchner <michael.mc.kirchner@deutschebahn.com>

*Date*: 2017/10/19

- Status: New
- Proposal type: (core design, process, ?)
- Targeted Release: <future release #, ex. 2.2>
- Associated PR: <link to GH PR in ansible/proposals if PR was submitted>
- Estimated time to implement: <X days, weeks, etc.>

## Motivation
Right now it does not seem to be possible to create kms encyption keys with ansible module.
The aws cli command has an option for that
aws kms create-key
I think this is an important feature.

**Comment by sivel** [comment]
I think this is more in alignment with a simple feature request instead of a proposal.

**Comment by willthames** [comment]
I'll raise a PR that covers this. I wrote an entire kms module before realising @tedder's aws_kms existed, oops, and I still need to fully reunify the two.

**Comment by tedder** [comment]
👍 @willthames, tag me when you PR it, or let me know what you have so far.

**Comment by rich-preservica** [comment]
Also looking for an update on this

**Comment by willthames** [comment]
Apologies, I raised the PR but didn't update this proposal

https://github.com/ansible/ansible/pull/31960

Although the PR says things like needs_rebase and needs_revision, which it does, it probably needs testing more. It worked for my use cases at the time, but I haven't needed it for a while.

Please add any further comments to the PR rather than here.
